name: .NET

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Branch Filestorage Action
      uses: moonrailgun/branch-filestorage-action@v1.2.2
      with:
        branch: graphtoken
        path: graphtoken.asc
    - name: test
      run: cat graphtoken.asc
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build .\TodoSynchronizer.CLI\TodoSynchronizer.CLI.csproj --no-restore -c Release
    - name: Test
      run: echo 999
    - name: Test
      run: .\TodoSynchronizer.CLI\bin\Release\net6.0\TodoSynchronizer.CLI.exe
